### PR TITLE
Update gcc-python-wrapper.c for Python 3.8

### PR DESCRIPTION
**Pull request by fishilico**
Commit 3a4b484eaeda ("Build on Python 3.8") updated `cpybuilder.py` but not `gcc-python-wrapper.c`. This results in the following error when building with Python 3.8:

    gcc-python-wrapper.c:188:1: error: converting to non-pointer type
    ‘long int’ from NULL [-Werror=conversion-null]
      188 | };
          | ^

### CODE REVIEW

**Comment by davidmalcolm** [comment]
Thanks for the patch; sorry for the delay in reviewing it.
